language: cpp

env:
  global:
    - DEPS_DIR=${HOME}/deps
    - BUILD_COVERAGE=${TRAVIS_BUILD_DIR}/coverage
    
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      group: deprecated-2017Q4
      compiler: gcc-8
      env:
        - VCPKG_TRIPLET=x64-linux
        - CC_COMPILER=gcc-8
        - CXX_COMPILER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - lcov

install:
  # Create deps dir
  - mkdir -p ${DEPS_DIR}

  # Set compiler vars
  - export CC=${CC_COMPILER}
  - export CXX=${CXX_COMPILER}

  # Install vcpkg and dependencies
  - |
    set -e
    mkdir -p $HOME/.cache
    mkdir -p ${DEPS_DIR}/vcpkg
    pushd ${DEPS_DIR}/vcpkg
    git init
    git remote add origin https://github.com/Microsoft/vcpkg.git
    git fetch origin master
    git checkout -b master origin/master
    ./bootstrap-vcpkg.sh
    popd
    
cache:
  directories:
    - ${DEPS_DIR}/vcpkg/installed
    - $HOME/.cache
    
script:
  - cmake --version
  - cd easyprospect-service
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
  - make
  - make test
  
codecov:
  token: "c6b52bca-999b-4557-a0c2-206a8bf02b31"
  
after_success:
  - wget https://github.com/linux-test-project/lcov/archive/v1.14.zip
  - unzip v1.14.zip
  - LCOV="`pwd`/lcov-1.14/bin/lcov"

  - ${LCOV} --capture --directory . --gcov-tool gcov-8 --capture --output-file coverage.info
  - ${LCOV} --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --gcov-tool gcov-8 --output-file coverage.info
  - ${LCOV} --gcov-tool gcov-8 --list coverage.info

  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  
